# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-GrowlClient
version:      0.02
version_from: lib/Net/GrowlClient.pm
installdirs:  site
requires:
    Carp:                          0
    Digest::MD5:                   0
    Digest::SHA:                   0
    Exporter:                      0
    IO::Socket:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
